name: CI

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: pnpm/action-setup@v4
        with:
          version: 9.4.0
          run_install: true
      - name: Build the plugin
        run: pnpm build
      - name: Check if the App builds successfully
        run: pnpm build
        working-directory: example
      - name: Biome checks
        run: pnpm check